export { default as About } from "@components/about";
export { default as Footer } from "@components/footer";
export { default as Hero } from "@components/hero";
export { default as Icon } from "@components/icon";
export { default as Layout } from "@components/layout";
export { default as Navbar } from "@components/navbar";
export { default as Skills } from "@components/skills";
export { default as SEO } from "@components/seo";
export { default as SectionTitle } from "@components/sectionTitle";
